add require for InternalOAuthError
A reference error occurs with "InternalOAuthError is not defined" when an error occurs getting the user profile: 
/app/node_modules/passport-bluemix/lib/strategy.js:44
            return done(new InternalOAuthError('Failed to fetch user profile', err)
                            ^
ReferenceError: InternalOAuthError is not defined